name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.HOST }}
      HTTP_PATH: ${{ secrets.HTTP_PATH }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: install packages
        run: make install
      - name: lint
        run: make lint
      - name: format
        run: make format
#      - name: python run
#        run: make python-run
#      - name: rust run
#        run: make rust-run